export const ADD_CONSTRUCTOR_COMPONENT = 'ADD_CONSTRUCTOR_COMPONENT';
export const DELETE_CONSTRUCTOR_COMPONENT = 'DELETE_CONSTRUCTOR_COMPONENT';  
export const CONSTRUCTER_ORDER = 'CONSTRUCTER_ORDER';